### ISSUE TITLE
Why doesn't call_function exist in v2?

### ISSUE THREAD

**Issue by 1232ynp** [googleapis/python-functions#242] opened 2023-01-25 16:13 UTC
v1 has call_function as shown below. Why is it not present in v2?

https://github.com/googleapis/python-functions/blob/c8835727e808c97bf3ec04b2732693e2eaa319fe/google/cloud/functions_v1/services/cloud_functions_service/client.py#L1081

**Comment by 1232ynp** [comment] 2023-01-26 08:21
v1 uses call_function to run CloudFunctions system tests. I wanted to do the same system test with v2.
Specifically, the system built with CloudFunctions + CloudScheduler + CloudPub/Sub is tested with the CI/CD step using CloudBuild.

**Comment by parthea** [comment] 2023-01-26 21:04
Hi @1232ynp, 

Thanks for reporting this issue an opening a pull request. The `call_function` functionality is not available in [functions v2 API](https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions#methods) itself. I'm going to close the PR as this feature is not present on the back end.

I will keep this issue open so that we can provide updates as we receive them from the API team.

Please use the following support page to reach out to the API support team directly: https://cloud.google.com/functions/docs/getting-support

Googlers see b/200729263

**Comment by parthea** [comment] 2023-04-15 15:29
I've filed a feature request in the [public issue tracker](https://cloud.google.com/support/docs/issue-trackers#trackers-list) here https://b.corp.google.com/issues/278353662. I'm going to close this issue as a duplicate of https://b.corp.google.com/issues/278353662.

**Closed by parthea** 2023-04-15 15:29 UTC
Labels: type: feature request, external, api: cloudfunctions
